import { test, expect } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dismissPlottingRules } from './planner-test-helpers';

// Opt-in: real writes, only against the disposable local validation server/database.
test('actual PDF -> real hall API -> PostgreSQL -> Three.js -> manual stall -> persisted layout', async ({ page, request }, info) => {
  test.skip(process.env['PDF_LIVE_VALIDATION'] !== 'isolated-local-db' || !process.env['PDF_REFERENCE_FILE'], 'Requires the isolated local validation API and a local PDF.');
  test.setTimeout(180_000);
  const pdf = readFileSync(process.env['PDF_REFERENCE_FILE']!);
  const evidence: Record<string, any> = { apiMocked: false, database: 'codex_pdf_live_20261008', fileHash: createHash('sha256').update(pdf).digest('hex'), limitations: ['Hall 9 grid region is a manually marked test sample, not automatic recognition of the complete hall.', 'Reference-texture identity does not establish pixel identity with other PDF engines.', 'No survey accuracy, automatic semantic reconstruction or height inference is certified.'] };
  const writes: { path: string; contentType: string; bytes: number }[] = [];
  const failedApi: { path: string; status: number }[] = [];
  page.on('request', r => { if (!['GET','OPTIONS'].includes(r.method())) writes.push({ path: new URL(r.url()).pathname, contentType: r.headers()['content-type'] ?? '', bytes: r.postDataBuffer()?.length ?? 0 }); });
  page.on('response', r => { if (r.url().startsWith('http://localhost:8080/') && r.status() >= 400) failedApi.push({ path: new URL(r.url()).pathname, status: r.status() }); });
  const pageErrors: string[] = [];
  page.on('pageerror', e => pageErrors.push(e.message));
  try {
    const list = await request.get('http://localhost:8080/api/halls?standalone=true');
    expect(list.status()).toBe(200);
    evidence.initialHallCount = (await list.json()).length;
    await page.addInitScript(() => localStorage.setItem('stall-planner.guided-tour.v1', 'completed'));
    await page.goto('/planner/halls');
    await expect(page.getByText("We couldn't load the halls", { exact: true })).toHaveCount(0);
    await page.getByRole('link', { name: /Import a floor plan/ }).first().click();
    await page.locator('input[type=file]').setInputFiles({ name: '8-9-10.pdf', mimeType: 'application/pdf', buffer: pdf });
    await expect(page.locator('.drawing-footer')).toBeVisible({ timeout: 90_000 });
    await expect(page.locator('app-pdf-three-scene').getByRole('status')).toContainText('Full-page overview');
    evidence.afterUpload = await page.evaluate(() => {
      const w = (window as any).ng.getComponent(document.querySelector('app-pdf-workspace'));
      const s = (window as any).ng.getComponent(document.querySelector('app-scene3d'));
      const layer = (window as any).ng.getComponent(document.querySelector('app-pdf-three-scene'));
      const p = w.inspection(), objects = w.doc().objects;
      return { pageCount: w.pageCount(), width: p.width, height: p.height, paths: p.paths.length, texts: p.texts.length, layers: p.layers.length, automaticObjects: objects.length, sharesRenderer: s.renderer === layer.renderer, sharesScene: s.scene === layer.scene };
    });
    expect(evidence.afterUpload.sharesRenderer).toBe(true);
    expect(evidence.afterUpload.automaticObjects).toBe(0);
    await page.locator('.pdf-import-sidebar').evaluate(e => e.scrollTop = 0);
    await page.screenshot({ path: 'test-results/pdf-live-full-plan.png' });
    await page.getByRole('button', { name: 'Calibrate scale', exact: true }).click();
    await page.getByText('Enter precise reference points', { exact: true }).click();
    await page.getByLabel('Reference coordinates: x, y per line').fill('1335.3299560546875,1200\n1344.1500244140625,1200');
    await page.getByRole('button', { name: 'Use reference coordinates', exact: true }).click();
    await page.getByLabel('Known distance (m)', { exact: true }).fill('1');
    await page.getByRole('button', { name: 'Apply to this page', exact: true }).click();
    await page.getByRole('button', { name: 'Trace outline', exact: true }).click();
    await page.getByText('Enter outline coordinates', { exact: true }).click();
    await page.getByLabel('Outline coordinates: x, y per line').fill('1327.530029296875,1090.780029296875\n1623.1199951171875,1090.780029296875\n1623.1199951171875,1329.1300048828125\n1327.530029296875,1329.1300048828125');
    await page.getByRole('button', { name: 'Create outline from coordinates', exact: true }).click();
    await page.getByLabel('Name', { exact: true }).fill('PDF validation — Hall 9 grid region (manual sample)');
    await page.getByLabel('Name', { exact: true }).blur();
    await page.getByRole('combobox', { name: 'Object type', exact: true }).selectOption('hall');
    await page.getByLabel('I reviewed this outline and its meaning').check();
    const sample = await page.evaluate(async () => {
      const w = (window as any).ng.getComponent(document.querySelector('app-pdf-workspace'));
      const o = w.selected(), k = w.activeCalibration().metresPerUnit;
      const x = Math.min(...o.points.map((p:any) => p.x)), y = Math.min(...o.points.map((p:any) => p.y));
      const width = Math.max(...o.points.map((p:any) => p.x))-x, height = Math.max(...o.points.map((p:any) => p.y))-y;
      const canvas = document.createElement('canvas'), scale = 2048/(Math.max(width,height)*Math.min(devicePixelRatio||1,2));
      await w.reader.render(canvas, scale, x*scale,y*scale,width*scale,height*scale);
      const pixels = canvas.getContext('2d')!.getImageData(0,0,canvas.width,canvas.height).data;
      const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', pixels))).map(n=>n.toString(16).padStart(2,'0')).join('');
      return { documentId:w.doc().id, points:o.points, k, x,y,width,height, hash, png:canvas.toDataURL('image/png') };
    });
    writeFileSync('test-results/pdf-live-source-crop.png', Buffer.from(sample.png.split(',')[1], 'base64'));
    const originalCanvas = await page.locator('app-scene3d canvas').elementHandle();
    const saveResponse = page.waitForResponse(r => r.url() === 'http://localhost:8080/api/halls' && r.request().method() === 'POST');
    await page.getByRole('button', { name: 'Save hall & open planner', exact: true }).click();
    const response = await saveResponse;
    evidence.hallSaveStatus = response.status();
    evidence.hallSaveBody = await response.json();
    expect(response.ok()).toBe(true);
    const saved = evidence.hallSaveBody;
    await expect(page).toHaveURL(new RegExp(`planner/editor\\?hallId=${saved.id}`));
    await dismissPlottingRules(page);
    await expect(page.getByLabel('PDF hall reference')).toContainText('Calibrated PDF crop', { timeout: 60_000 });
    await expect(page.getByText('Offline sample', { exact: true })).toHaveCount(0);
    await expect(page.getByText('No halls on the server', { exact: false })).toHaveCount(0);
    evidence.sameCanvasAfterImport = await originalCanvas!.evaluate(c => c === document.querySelector('app-scene3d canvas'));
    const state = await page.evaluate(async () => {
      const p = (window as any).ng.getComponent(document.querySelector('app-planner-page'));
      const s = (window as any).ng.getComponent(document.querySelector('app-scene3d'));
      const plane = s.hallGroup.getObjectByName('pdf-hall-reference'), canvas = plane.material.map.image;
      const pixels = canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
      const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', pixels))).map(n=>n.toString(16).padStart(2,'0')).join('');
      let wallBoxes=0;s.hallGroup.traverse((c:any)=>{if(c.geometry?.type==='BoxGeometry')wallBoxes++;});
      return {hall:p.currentHall(),stalls:p.currentStalls().length,hash,textureWidth:canvas.width,textureHeight:canvas.height,wallBoxes,planeWidth:plane.geometry.parameters.width,planeLength:plane.geometry.parameters.height};
    });
    evidence.importedScene = state;
    const expected = sample.points.map((p:any)=>({x:(p.x-sample.x-sample.width/2)*sample.k,z:(p.y-sample.y-sample.height/2)*sample.k}));
    evidence.maximumBoundaryErrorMetres = Math.max(...state.hall.boundary.flatMap((p:any,i:number)=>[Math.abs(p.x-expected[i].x),Math.abs(p.z-expected[i].z)]));
    expect(evidence.maximumBoundaryErrorMetres).toBeLessThan(1e-10);
    expect(state.hash).toBe(sample.hash);
    expect(state.stalls).toBe(0);
    expect(state.wallBoxes).toBe(0);
    expect(state.planeWidth).toBeCloseTo(sample.width*sample.k,10);
    expect(state.planeLength).toBeCloseTo(sample.height*sample.k,10);
    expect(evidence.sameCanvasAfterImport).toBe(true);
    await page.screenshot({ path: 'test-results/pdf-live-three-layout.png' });
    await page.reload();
    await dismissPlottingRules(page);
    await expect(page.getByLabel('Show original drawing')).toBeVisible();
    const reloaded = await request.get(`http://localhost:8080/api/halls/${saved.id}`);
    expect(reloaded.status()).toBe(200);
    expect((await reloaded.json()).boundary).toEqual(saved.boundary);
    evidence.hallReloadVerified = true;
    const add = page.locator('app-add-stall-form');
    await add.getByLabel('Shop or stall name').fill('Validation only — manual 3 × 3 m stall');
    await add.getByLabel('Width (m)', { exact: true }).fill('3');
    await add.getByLabel('Length (m)', { exact: true }).fill('3');
    await add.getByLabel('Height (m)', { exact: true }).fill('2.5');
    await add.getByRole('button', { name: 'Add Shop (then drag on grid)' }).click();
    await expect.poll(() => page.evaluate(() => (window as any).ng.getComponent(document.querySelector('app-planner-page')).currentStalls().length)).toBe(1);
    const saveLayoutResponse = page.waitForResponse(r=>r.url().endsWith('/api/layout/save')&&r.request().method()==='POST');
    await page.getByRole('button',{name:'Save layout',exact:true}).click();
    const layoutResponse = await saveLayoutResponse;
    evidence.layoutSaveStatus=layoutResponse.status();
    evidence.layoutSaveBody=await layoutResponse.json();
    expect(layoutResponse.ok()).toBe(true);
    await page.screenshot({path:'test-results/pdf-live-manual-stall.png'});
    evidence.stallPreview = await page.evaluate(() => {
      const p=(window as any).ng.getComponent(document.querySelector('app-planner-page'));
      return {layoutId:p.store.selectedSavedId(),stalls:p.currentStalls()};
    });
    const layout = await request.get(`http://localhost:8080/api/layout/${evidence.stallPreview.layoutId}`);
    expect(layout.status()).toBe(200);
    evidence.persistedLayout=await layout.json();
    expect(evidence.persistedLayout.stalls).toHaveLength(1);
    expect(writes.every(w=>w.contentType.includes('application/json'))).toBe(true);
    expect(writes.some(w=>/pdf-import|halls\/import/.test(w.path))).toBe(false);
    expect(failedApi).toEqual([]);
    expect(pageErrors).toEqual([]);
    evidence.verdict='PASS for local rendering, manually reviewed geometry, real API/database persistence and manual stall creation. Automatic full PDF-to-3D semantic reconstruction is NOT implemented.';
  } finally {
    evidence.writes=writes;evidence.failedApi=failedApi;evidence.pageErrors=pageErrors;
    writeFileSync('test-results/pdf-live-validation.json',JSON.stringify(evidence,null,2));
    await info.attach('live-validation-evidence',{body:JSON.stringify(evidence,null,2),contentType:'application/json'});
  }
});
